
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EMPTY EQUAL LBR NON_TERMINAL RBR START TERMINALStart : START Rules Rules : Rule\n              | Rule Rules\n    Rule : NON_TERMINAL EQUAL LBR Expr RBR Expr : Term\n             | Term Expr\n    Term : TERMINALTerm : NON_TERMINALTerm : EMPTY'
    
_lr_action_items = {'START':([0,],[2,]),'$end':([1,3,4,6,14,],[0,-1,-2,-3,-4,]),'NON_TERMINAL':([2,4,8,9,11,12,13,14,],[5,5,9,-8,9,-7,-9,-4,]),'EQUAL':([5,],[7,]),'LBR':([7,],[8,]),'TERMINAL':([8,9,11,12,13,],[12,-8,12,-7,-9,]),'EMPTY':([8,9,11,12,13,],[13,-8,13,-7,-9,]),'RBR':([9,10,11,12,13,15,],[-8,14,-5,-7,-9,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Start':([0,],[1,]),'Rules':([2,4,],[3,6,]),'Rule':([2,4,],[4,4,]),'Expr':([8,11,],[10,15,]),'Term':([8,11,],[11,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Start","S'",1,None,None,None),
  ('Start -> START Rules','Start',2,'p_Start','parser.py',84),
  ('Rules -> Rule','Rules',1,'p_Rules','parser.py',89),
  ('Rules -> Rule Rules','Rules',2,'p_Rules','parser.py',90),
  ('Rule -> NON_TERMINAL EQUAL LBR Expr RBR','Rule',5,'p_Rule','parser.py',96),
  ('Expr -> Term','Expr',1,'p_Expr','parser.py',101),
  ('Expr -> Term Expr','Expr',2,'p_Expr','parser.py',102),
  ('Term -> TERMINAL','Term',1,'p_Term_terminal','parser.py',108),
  ('Term -> NON_TERMINAL','Term',1,'p_Term_non_terminal','parser.py',113),
  ('Term -> EMPTY','Term',1,'p_Term_Empty','parser.py',118),
]
